#include "style_props_common.h"
STYLE_PROP(left, left, float, -1.f, { el.notifyPositionDataChanged(); })
STYLE_PROP(right, right, float, -1.f, { el.notifyPositionDataChanged(); })
STYLE_PROP(top, top, float, -1.f, { el.notifyPositionDataChanged(); })
STYLE_PROP(bottom, bottom, float, -1.f, { el.notifyPositionDataChanged(); })
STYLE_PROP(width, width, float, -1.f, { el.notifyPositionDataChanged(); })
STYLE_PROP(height, height, float, -1.f, { el.notifyPositionDataChanged(); })
STYLE_PROP2(borderWidth, border-width, float, 0.f)
STYLE_PROP2(borderColor, border-color, GuiColor, GuiColor())
STYLE_PROP2(backgroundColor, background-color, GuiColor, GuiColor())
STYLE_PROP2(backgroundImage, background-image, GuiNinepatchImage, GuiNinepatchImage())